all:
  hosts:
    ansible.home.lab:
      ansible_connection: local
  children:
    testing:
      hosts:
        server1.home.lab:
        server2.home.lab:
    mac:
      hosts:
        tycho:
    ubuntu:
      hosts:
        server1.home.lab:
        server2.home.lab:
